cl.exe > "pipeline.cpp1.ii" -D__CUDA_ARCH__=500 -D__CUDA_ARCH_LIST__=500 -D__NV_LEGACY_LAUNCH -nologo -E -TP  -DCUDA_DOUBLE_MATH_FUNCTIONS -EHsc -D__CUDACC__ -D__NVCC__  "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\bin/../include"    -D__CUDACC_VER_MAJOR__=12 -D__CUDACC_VER_MINOR__=4 -D__CUDACC_VER_BUILD__=99 -D__CUDA_API_VER_MAJOR__=12 -D__CUDA_API_VER_MINOR__=4 -D__NVCC_DIAG_PRAGMA_SUPPORT__=1 -FI "cuda_runtime.h" "pipeline.cu" 
cicc --ms_c++14 --microsoft_version=1938 --msvc_target_version=1938 --compiler_bindir "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.38.33130/bin/HostX64/x64/../../../../../../.." --sdk_dir "C:/Program Files (x86)/Windows Kits/10/" --display_error_number --orig_src_file_name "pipeline.cu" --orig_src_path_name "C:\Users\micro\git\GPUs-Energy-Windows\Instructions_Microbenchmarks\pipeline.cu" --allow_managed  -arch compute_50 -m64 --no-version-ident -ftz=0 -prec_div=1 -prec_sqrt=1 -fmad=1 --include_file_name "pipeline.fatbin.c" -tused --module_id_file_name "pipeline.module_id" --gen_c_file_name "pipeline.cudafe1.c" --stub_file_name "pipeline.cudafe1.stub.c" --gen_device_file_name "pipeline.cudafe1.gpu"  "pipeline.cpp1.ii" -o "pipeline.ptx"
ptxas -arch=sm_50 -m64 -O0 "pipeline.ptx"  -o "pipeline.cubin" 
fatbinary --create="pipeline.fatbin" -64 --cmdline="-O0 " --cicc-cmdline="-ftz=0 -prec_div=1 -prec_sqrt=1 -fmad=1 " "--image3=kind=elf,sm=50,file=pipeline.cubin" --embedded-fatbin="pipeline.fatbin.c" 
cl.exe -Fo"pipeline.obj" -D__CUDA_ARCH__=500 -D__CUDA_ARCH_LIST__=500 -D__NV_LEGACY_LAUNCH -nologo -c -TP  -DCUDA_DOUBLE_MATH_FUNCTIONS -EHsc "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\bin/../include"   "pipeline.cudafe1.cpp" 
nvlink -optf "a_dlink.cubin.optf"
fatbinary --create="a_dlink.fatbin" -64 --cmdline="-O0 " --cicc-cmdline="-ftz=0 -prec_div=1 -prec_sqrt=1 -fmad=1 " -link "--image3=kind=elf,sm=50,file=a_dlink.cubin" --embedded-fatbin="a_dlink.fatbin.c" 
cl.exe -Fo"a_dlink.obj" -D__CUDA_ARCH_LIST__=500 -D__NV_LEGACY_LAUNCH -nologo -c -TP -EHsc -DFATBINFILE="\"a_dlink.fatbin.c\"" -DREGISTERLINKBINARYFILE="\"a_dlink.reg.c\"" -I. -D__NV_EXTRA_INITIALIZATION= -D__NV_EXTRA_FINALIZATION= -D__CUDA_INCLUDE_COMPILER_INTERNAL_HEADERS__  "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\bin/../include"    -D__CUDACC_VER_MAJOR__=12 -D__CUDACC_VER_MINOR__=4 -D__CUDACC_VER_BUILD__=99 -D__CUDA_API_VER_MAJOR__=12 -D__CUDA_API_VER_MINOR__=4 -D__NVCC_DIAG_PRAGMA_SUPPORT__=1 "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\bin\crt\link.stub" 
cl.exe -Fe"a.exe" -D__CUDA_ARCH_LIST__=500 -D__NV_LEGACY_LAUNCH -nologo "a_dlink.obj" "pipeline.obj" -link -INCREMENTAL:NO -LIBPATH:"C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.4/include" -LIBPATH:"CUDA_DIR/lib64" cuda.lib cudart.lib nvml.lib   "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\bin/../lib/x64"  cudadevrt.lib  cudart_static.lib
